    version: 2
    jobs:
      build:
        docker:
          - image: circleci/buildpack-deps:stretch
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Build Docker image
              command: docker build -t spbu/cae:latest .
          - run:    
              name: Test Docker image core imports (NumPy, FEniCS)
              command: mkdir data && docker run -p 8890:8892  -e USER_PASS=Scientific -d $(pwd)/data/:/opt/notebook/ spbu/cae:latest /bin/bash -c "python -c \"import numpy; print(numpy.__path__); from dolfin import *;\" "
              
    workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: master